# GNU utilities
brew "coreutils"
brew "gnu-sed"
brew "findutils"
brew "gawk"

# cask "karabiner-elements"
brew "kanata"
brew "FelixKratz/formulae/borders"
cask "nikitabobko/tap/aerospace"
cask "maccy"
cask "latest"
cask "shottr"
cask "monitorcontrol"
cask "wezterm"
cask "scroll-reverser"
