#!/bin/sh

install_brew() {
  if ! command -v brew >/dev/null 2>&1; then
    echo "Homebrew not found. Installing Homebrew..."
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    return
  fi
  echo "Homebrew is already installed."
}

main() {
  xcode-select --install
  install_brew
  brew bundle --file=./Brewfile
}

main
