#!/bin/sh

install_brew() {
  if ! command -v brew >/dev/null 2>&1; then
    echo "Homebrew not found. Installing Homebrew..."
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    return
  fi
  echo "Homebrew is already installed."
}

install_virtual_hid_driver() {
  curl -L -o /tmp/VirtualHIDDriver.pkg https://github.com/pqrs-org/Karabiner-DriverKit-VirtualHIDDevice/releases/download/v6.14.0/Karabiner-DriverKit-VirtualHIDDevice-6.14.0.pkg
  sudo installer -pkg /tmp/VirtualHIDDriver.pkg -target /
  /Applications/.Karabiner-VirtualHIDDevice-Manager.app/Contents/MacOS/Karabiner-VirtualHIDDevice-Manager activate
}

brew_services() {
  sudo brew services start kanata
  brew services start borders
}

main() {
  xcode-select --install
  install_virtual_hid_driver
  install_brew
  brew_services
  brew bundle --file=./Brewfile
}

main
